language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_install:
- npm install -g swagger
install:
- npm install
notifications:
  email:
    recipients:
    - bsjun@kr.ibm.com
    on_success: change
    on_failure: always
deploy:
- provider: bluemixcloudfoundry
  api: https://api.ng.bluemix.net
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  manifest: manifest.yml
  on:
    branch: test
